import type { Metadata } from 'next';
import './globals.css';
import Navbar from '../components/navbar';
import QueryProvider from '@/providers/QueryProvider';
import AuthProvider from '@/providers/AuthProvider';
import { Toaster } from '@/components/ui/sonner';
import { ReactNode } from 'react';
import Footer from '@/components/footer';

export const metadata: Metadata = {
  title: 'Car Shop Course',
  description: 'Generated by create next app',
};

const RootLayout = ({
  children,
}: Readonly<{
  children: ReactNode;
}>) => {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <QueryProvider>
            <Navbar />

            <main className="container mx-auto px-5 py-10">{children}</main>

            <Toaster />

            <Footer />
          </QueryProvider>
        </AuthProvider>
      </body>
    </html>
  );
};

export default RootLayout;
