import type { Metadata } from 'next';
import './globals.css';
import Navbar from '../components/navbar';
import QueryProvider from '@/providers/QueryProvider';
import { Toaster } from '@/components/ui/sonner';

export const metadata: Metadata = {
  title: 'Car Shop Course',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <QueryProvider>
          <Navbar />
          <main className="container mx-auto px-5 pt-10">{children}</main>
          <Toaster />
        </QueryProvider>
      </body>
    </html>
  );
}
